import os
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.tensorboard import SummaryWriter


# input_dim : 32 coordinates (16 joints * 2 for x and y)
class AramandiClassifier(nn.Module):
    def __init__(self, input_dim=32, hidden_dim=128, output_dim=2): # Expanded tracking matrix
        super(AramandiClassifier, self).__init__()
        self.network = nn.Sequential(
            nn.Linear(input_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, output_dim)
        )
    def forward(self, x):
        return self.network(x)


def generate_mock_data():
    """Loads real extracted landmarks generated by prepare_data.py"""
    if os.path.exists('X_features.npy') and os.path.exists('y_labels.npy'):
        print("[Trainer] Loading genuine processed dataset from disk...")
        X = np.load('X_features.npy')
        y = np.load('y_labels.npy')
        return torch.FloatTensor(X), torch.LongTensor(y)
    else:
        print("[Trainer] Real data files not found. Falling back to synthetic simulation data...")
        np.random.seed(42)
        num_samples = 200
        X = np.random.rand(num_samples, 32).astype(np.float32)
        y = np.zeros(num_samples, dtype=np.int64)
        X[100:, 8:12] += 0.3  
        X[100:, 10:14] += 0.5
        y[100:] = 1          
        return torch.FloatTensor(X), torch.LongTensor(y)


def train_pipeline():
    print("[Trainer] Initializing tensor vectors...")
    X, y = generate_mock_data()
   
    # Instantiate the network topology
    model = AramandiClassifier()
   
    # Define production standard Cross-Entropy Loss and Adam Optimizer
    criterion = nn.CrossEntropyLoss()
   
    # ADJUSTMENT: Lowered learning rate from 0.01 to 0.001 for subtle geometric nuance optimization
    optimizer = optim.Adam(model.parameters(), lr=0.001)
   
    # ─── SYSTEM-AUTOMATED LOGGING ───
    # This instantiation automatically builds the 'runs/aramandi_experiment' directories
    writer = SummaryWriter("runs/aramandi_experiment")
   
    print("[Trainer] Commencing backpropagation optimization loops...")
   
    # ADJUSTMENT: Increased epochs from 100 to 500 to let weights properly converge
    for epoch in range(1, 501):  
        model.train()
        optimizer.zero_grad() # Clear gradients from previous iteration
       
        # Forward pass
        outputs = model(X)
        loss = criterion(outputs, y)
       
        # Backward pass (Backpropagation)
        loss.backward()
        optimizer.step()
       
        # Performance metric evaluation
        _, predicted = torch.max(outputs, 1)
        correct = (predicted == y).sum().item()
        accuracy = (correct / y.size(0)) * 100
       
        # ─── AUTOMATED TENSORBOARD TELEMETRY ───
        # Writes the math scores directly into the binary logging folder
        writer.add_scalar("Loss/train", loss.item(), epoch)
        writer.add_scalar("Accuracy/train", accuracy, epoch)
       
        if epoch % 50 == 0 or epoch == 1:
            print(f"Epoch {epoch}/500 ── Loss: {loss.item():.4f} ── Accuracy: {accuracy:.1f}%")
           
    # Safely close the logging streams
    writer.close()
   
    # ─── SYSTEM-AUTOMATED SERIALIZATION ───
    # Ensures the target directory exists and saves the model parameters automatically
    os.makedirs("uploads", exist_ok=True)
    target_weights_path = "uploads/aramandi_classifier.pth"
    torch.save(model.state_dict(), target_weights_path)
   
    print(f"\n[Success] Execution complete! Model serialized to '{target_weights_path}'")


if __name__ == "__main__":
    train_pipeline()